name: Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "스크립트 실행"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            cd /mnt/ssd/front/team

            echo "Git 최신화 시작"
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            echo "Git 최신화 완료"
            npm install
            echo "패키지 설치 완료"
            npm run build
            echo "빌드 완료"
            sudo rm -rf /mnt/ssd/nginx/www/team/*
            sudo cp -r out/* /mnt/ssd/nginx/www/team/
            echo "빌드 파일 복사 완료"
            
            sudo chown -R seopia:www-data /mnt/ssd/nginx/www/team
            echo "폴더 소유자 변경 완료"

            sudo systemctl restart nginx
            echo "nginx 재시작 완료"
